//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class examLog
    {
        public int idWho { get; set; }
        public string login { get; set; }
        public int password { get; set; }
    }
}
